-- ARTISTA = TALLER
CREATE TABLE ARTISTA(
    CODIGO INT PRIMARY KEY,
    NOMBRE_ARTISTICO VARCHAR(50) NOT NULL UNIQUE,
    GENERO_MUSICAL VARCHAR(30) NOT NULL,
    NOMBRE_OFICIAL VARCHAR(50),
    NUMERO_INTEGRANTES INT,
    TIPO_ARTISTA VARCHAR(10),
    CHECK(TIPO_ARTISTA IN ('Solista','Grupo')),
    CHECK((TIPO_ARTISTA = 'Solista' AND NOMBRE_OFICIAL IS NOT NULL AND NUMERO_INTEGRANTES IS NULL) 
          OR (TIPO_ARTISTA = 'Grupo' AND NOMBRE_OFICIAL IS NULL AND NUMERO_INTEGRANTES IS NOT NULL)),
    CHECK(CODIGO >= 0),
    CHECK(NUMERO_INTEGRANTES > 1)
);

-- ALBUM = MECANICO

CREATE TABLE ALBUM(
    CODIGO INT PRIMARY KEY,
    TITULO VARCHAR(30) NOT NULL,
    ANO_LANZAMIENTO INT NOT NULL,
    CREDITOS VARCHAR(255) NOT NULL,
    CODIGO_ARTISTA INT NOT NULL,
    FOREIGN KEY (CODIGO_ARTISTA) REFERENCES ARTISTA(CODIGO),
    CHECK(CODIGO >= 0),
    CHECK(CODIGO_ARTISTA >= 0),
    CHECK(ANO_LANZAMIENTO > 0)
);

-- REPARACION = CANCION

CREATE TABLE CANCION(
    CODIGO INT PRIMARY KEY,
    TITULO VARCHAR(30) NOT NULL,
    FECHA_LANZAMIENTO DATE NOT NULL,
    DURACION INT NOT NULL,
    CODIGO_ALBUM INT,
    CODIGO_INSPIRACION INT, 
    FOREIGN KEY(CODIGO_INSPIRACION) REFERENCES CANCION(CODIGO),
    FOREIGN KEY(CODIGO_ALBUM) REFERENCES ALBUM(CODIGO),

    CHECK(CODIGO != CODIGO_INSPIRACION),
    CHECK(CODIGO >= 0),
    CHECK(CODIGO_ALBUM >= 0),
    CHECK(CODIGO_INSPIRACION >= 0),
    CHECK(DURACION >= 0)
);


-- INTO PARA PRUEBAS--
INSERT INTO ARTISTA (CODIGO, NOMBRE_ARTISTICO, GENERO_MUSICAL, NOMBRE_OFICIAL, NUMERO_INTEGRANTES, TIPO_ARTISTA)
VALUES (1, 'Solaris', 'Rock', 'Carlos Pérez', NULL, 'Solista');

INSERT INTO ARTISTA (CODIGO, NOMBRE_ARTISTICO, GENERO_MUSICAL, NOMBRE_OFICIAL, NUMERO_INTEGRANTES, TIPO_ARTISTA)
VALUES (2, 'Los Tornillos', 'Pop', NULL, 4, 'Grupo');

INSERT INTO ARTISTA (CODIGO, NOMBRE_ARTISTICO, GENERO_MUSICAL, NOMBRE_OFICIAL, NUMERO_INTEGRANTES, TIPO_ARTISTA)
VALUES (3, 'Mecánica Sonora', 'Electrónica', NULL, 3, 'Grupo');

INSERT INTO ALBUM (CODIGO, TITULO, ANO_LANZAMIENTO, CREDITOS, CODIGO_ARTISTA)
VALUES (1, 'Ritmos del Sol', 2020, 'Carlos Pérez - Composición y Producción', 1);

INSERT INTO ALBUM (CODIGO, TITULO, ANO_LANZAMIENTO, CREDITOS, CODIGO_ARTISTA)
VALUES (2, 'Ciclo de Vida', 2022, 'Los Tornillos - Interpretación y Producción', 2);

INSERT INTO ALBUM (CODIGO, TITULO, ANO_LANZAMIENTO, CREDITOS, CODIGO_ARTISTA)
VALUES (3, 'Engranajes Sonoros', 2023, 'Mecánica Sonora - Composición y Producción', 3);

INSERT INTO CANCION (CODIGO, TITULO, FECHA_LANZAMIENTO, DURACION, CODIGO_ALBUM, CODIGO_INSPIRACION)
VALUES (1, 'Luz del Amanecer', '2020-05-15', 210, 1, NULL);

INSERT INTO CANCION (CODIGO, TITULO, FECHA_LANZAMIENTO, DURACION, CODIGO_ALBUM, CODIGO_INSPIRACION)
VALUES (2, 'Velocidad Máxima', '2022-08-20', 180, 2, NULL);

INSERT INTO CANCION (CODIGO, TITULO, FECHA_LANZAMIENTO, DURACION, CODIGO_ALBUM, CODIGO_INSPIRACION)
VALUES (3, 'Revoluciones', '2023-02-10', 240, 3, 1);
