// ARTISTA = TALLER
CREATE TABLE ARTISTA(
    CODIGO INT PRIMARY KEY,
    NOMBRE_ARTISTICO VARCHAR(50) NOT NULL,
    GENERO_MUSICAL VARCHAR(30) NOT NULL,
    NOMBRE_OFICIAL VARCHAR(50),
    NUMERO_INTEGRANTES INT,
    TIPO_ARTISTA VARCHAR(10),
    CHECK(TIPO_ARTISTA IN ('Solista','Banda')),
    CHECK((TIPO_ARTISTA = 'Solista' AND NOMBRE_OFICIAL IS NOT NULL AND NUMERO_INTEGRANTES IS NULL) 
          OR (TIPO_ARTISTA = 'Banda' AND NOMBRE_OFICIAL IS NULL AND NUMERO_INTEGRANTES IS NOT NULL)),
    CHECK(CODIGO >= 0),
    CHECK(NUMERO_INTEGRANTES >= 0)
);

// ALBUM = MECANICO

CREATE TABLE ALBUM(
    CODIGO INT PRIMARY KEY,
    TITULO VARCHAR(30) NOT NULL,
    ANO_LANZAMIENTO INT NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    CODIGO_ARTISTA INT NOT NULL,
    FOREIGN KEY (CODIGO_ARTISTA) REFERENCES ARTISTA(CODIGO),
    CHECK(CODIGO >= 0),
    CHECK(CODIGO_ARTISTA >= 0),
    CHECK(ANO_LANZAMIENTO >= 0)
);

// REPARACION = CANCION

CREATE TABLE CANCION(
    CODIGO INT PRIMARY KEY,
    TITULO VARCHAR(30) NOT NULL,
    FECHA_LANZAMIENTO DATE NOT NULL,
    DURACION INT NOT NULL,
    CODIGO_ALBUM INT,
    CODIGO_INSPIRACION INT, 
    FOREIGN KEY(CODIGO_INSPIRACION) REFERENCES CANCION(CODIGO),
    FOREIGN KEY(CODIGO_ALBUM) REFERENCES ALBUM(CODIGO),
    CHECK(CODIGO != CODIGO_INSPIRACION),
    CHECK(CODIGO >= 0),
    CHECK(CODIGO_ALBUM >= 0),
    CHECK(CODIGO_INSPIRACION >= 0),
    CHECK(DURACION >= 0)
);
